##
## Bitnami Redis — local development overrides
##
## Chart: https://github.com/bitnami/charts/tree/main/bitnami/redis
##

image:
  tag: latest

architecture: standalone

auth:
  enabled: false

master:
  persistence:
    size: 1Gi
  resources:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      cpu: 250m
      memory: 128Mi
