##
## Redpanda — local development overrides
##
## Chart: https://github.com/redpanda-data/helm-charts
##

resources:
  cpu:
    cores: 1
  memory:
    container:
      max: 1536Mi
    redpanda:
      memory: 1Gi
      reserveMemory: 256Mi

storage:
  persistentVolume:
    size: 5Gi

statefulset:
  replicas: 1

console:
  enabled: true
  ingress:
    className: ""
  service:
    targetPort: 8080

tls:
  enabled: false

auth:
  sasl:
    enabled: false

tuning:
  tune_aio_events: false
