replicaCount: 1

image:
  repository: ghcr.io/cyberfabric/insight-front
  tag: "latest"
  pullPolicy: Always

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  className: nginx
  annotations: {}
  host: ""

oidc:
  issuer: ""
  clientId: ""

resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 200m
    memory: 128Mi
