apiVersion: v1
kind: ConfigMap
metadata:
  name: clickhouse-config
  namespace: data
  labels:
    app: clickhouse
data:
  cluster.xml: |
    <clickhouse>
        <remote_servers>
            <default>
                <shard>
                    <replica>
                        <host>clickhouse</host>
                        <port>9000</port>
                    </replica>
                </shard>
            </default>
        </remote_servers>

        <macros>
            <shard>1</shard>
            <replica>1</replica>
            <cluster>default</cluster>
        </macros>
    </clickhouse>
  default.xml: |
    <clickhouse>
        <users>
            <default>
                <password>clickhouse</password>
                <networks>
                    <ip>::/0</ip>
                </networks>
                <profile>default</profile>
                <access_management>1</access_management>
            </default>
        </users>
    </clickhouse>
